# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('url', models.URLField(unique=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('comment', models.TextField(blank=True, default='', verbose_name='comentário')),
                ('rating', models.IntegerField(verbose_name='classificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.Course', verbose_name='curso')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('email', 'course')]),
        ),
    ]
